name: ntrulpr1013
type: kem
claimed-nist-level: 4
claimed-security: IND-CCA2
length-public-key: 1455
length-secret-key: 1773
length-ciphertext: 1583
length-shared-secret: 32
nistkat-sha256: 6b1dfcc1ec5b899cdc75e3cc3e320cd45a2bcdbf1ae1a29e1b7eadcd94f02e06
principal-submitters:
  - Daniel J. Bernstein
  - Billy Bob Brumley
  - Ming-Shing Chen
  - Chitchanok Chuengsatiansup
  - Tanja Lange
  - Adrian Marotzke
  - Bo-Yuan Peng
  - Nicola Tuveri
  - Christine van Vredendaal
  - Bo-Yin Yang
implementations:
    - name: clean
      version: supercop-20210604 via https://github.com/mkannwischer/package-pqclean/tree/5714c895/ntruprime
    - name: avx2
      version: supercop-20210604 via https://github.com/mkannwischer/package-pqclean/tree/5714c895/ntruprime
      supported_platforms:
          - architecture: x86_64
            operating_systems:
                - Linux
                - Darwin
            required_flags:
                - avx2
