name: SPHINCS+
type: signature
claimed-nist-level: 3
length-public-key: 48
length-secret-key: 96
length-signature: 16224
testvectors-sha256: 56d771d34a000a0f2a03e0660202bc7cc82f089346c2e0ea5eaf55a792e66a8c
nistkat-sha256: 92eed523fc2f48b66826929b49a58d44c46aaa2c286a6d0e822a8d1e34555121
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
implementations:
    - name: clean
      version: https://github.com/sphincs/sphincsplus/commit/77755c94d0bc744478044d6efbb888dc13156441
    - name: avx2
      version: https://github.com/sphincs/sphincsplus/commit/77755c94d0bc744478044d6efbb888dc13156441
      supported_platforms:
        - architecture: x86_64
          required_flags:
            - avx2
