name: "RAINBOW(256,96,36,64) - circumzenithal"
type: signature
claimed-nist-level: 5
length-public-key: 536136
length-secret-key: 1408736
length-signature: 212
nistkat-sha256: fba7a186c7f809da0d7ee0dcbc64d2573d824b44e539539b30c7ef1a36911760
testvectors-sha256: 917d50fa2bd37eacbc977a877bc50b5f3dcbed7c5d9e7baf02bde13f25b0fbc7
principal-submitters:
  - Jintai Ding
auxiliary-submitters:
  - Ming-Shing Chen
  - Matthias Kannwischer
  - Jacques Patarin
  - Albrecht Petzoldt
  - Dieter Schmidt
  - Bo-Yin Yang
implementations:
    - name: clean
      version: https://github.com/fast-crypto-lab/rainbow-submission-round2/commit/173ada0e077e1b9dbd8e4a78994f87acc0c92263
