name: SPHINCS+
type: signature
claimed-nist-level: 1
length-public-key: 32
length-secret-key: 64
length-signature: 17088
testvectors-sha256: 8a2d4399b3d1282530804d319dc4fb91fa66c3e4c42bd7b859a3eaa96c5f515f
nistkat-sha256: a8b966844b0c9bb2d954d95d25777bd548ee3dcb78e0833de8333a033d24cacb
principal-submitters:
  - Andreas Hülsing
auxiliary-submitters:
  - Jean-Philippe Aumasson
  - Daniel J. Bernstein,
  - Christoph Dobraunig
  - Maria Eichlseder
  - Scott Fluhrer
  - Stefan-Lukas Gazdag
  - Panos Kampanakis
  - Stefan Kölbl
  - Tanja Lange
  - Martin M. Lauridsen
  - Florian Mendel
  - Ruben Niederhagen
  - Christian Rechberger
  - Joost Rijneveld
  - Peter Schwabe
implementations:
    - name: clean
      version: https://github.com/sphincs/sphincsplus/commit/77755c94d0bc744478044d6efbb888dc13156441
    - name: aesni
      version: https://github.com/sphincs/sphincsplus/commit/77755c94d0bc744478044d6efbb888dc13156441
      supported_platforms:
        - architecture: x86_64
          required_flags:
            - aes
